### PR TITLE
prep: episode 7

### PR DESCRIPTION
**Pull request by fearocanity**
## Description

Please provide a brief description of your changes here.

## Checklist

Setupping Frames:
- [ ] I Have disabled the `actions/init-banner`.
- [ ] I Have changed the `frameiterator` file to `1`.
- [ ] I Have setupped the `config.conf`.
- [ ] I Have deleted the old frames and replaced the new frames.
- [ ] I Have created a new Album and get the Album ID (optional).
- [ ] I Have setupped the subtitles (optional).

---

`QA`: After you pushed the changes:
- [ ] Have you enabled `actions/init-banner`?
- [ ] I Have confimed it is working.
- [ ] Is it visible to public?

### CODE REVIEW

**Review by kenny95002 — APPROVED** [review]

**Comment by fearocanity** [comment]
Wait, dont push it yet.

**Comment by kenny95002** [comment]
> Wait, dont push it yet.

my bad sorry

**Review by kenny95002 — APPROVED** [review]
looks good now

**Comment by fearocanity** [comment]
I'll just close this, since you have pushed the config.
Also you have your sub_posting enabled, you have to paste the subtitle in fb/subtitle_en.ass

**Comment by fearocanity** [comment]
> looks good now

We just need to delete those DOS escapes in config.conf

**Comment by kenny95002** [comment]
> I'll just close this, since you have pushed the config. Also you have your sub_posting enabled, you have to paste the subtitle in fb/subtitle_en.ass

Ill upload the file later, Thank you very much for your help.

**Comment by kenny95002** [comment]
> > looks good now
> 
> We just need to delete those DOS escapes in config.conf

so thats why the conflict happened?

**Pull request closed without merging**
